version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: wg-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: wg_dev
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./packages/server/prisma/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - wg-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev_user -d wg_dev"]
      interval: 10s
      timeout: 5s
      retries: 5



volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  wg-network:
    driver: bridge
    name: wg-network